feat: refactor task creation
atoma-network/atoma-contracts pull request #108
Opened 2024-10-29 12:06 UTC by jorgeantonio21

2024-10-29 14:44 UTC, Cifko requested changes

2024-10-29 15:36 UTC, jorgeantonio21 commented on sui/cli/src/main.rs
> +        #[arg(short = 'r', long)]
Addressed

2024-10-29 15:37 UTC, Cifko requested changes

2024-10-29 15:37 UTC, Cifko commented on sui/cli/src/main.rs
> +        #[arg(short = 's', long)]
`s` is `security_level` 😄

2024-10-29 16:22 UTC, jorgeantonio21 commented on sui/cli/src/main.rs
> +        #[arg(short = 's', long)]
Addressed, changed the security level short arg

2024-10-30 10:58 UTC, Cifko approved these changes

2024-10-30 16:02 UTC, merged